namespace Backend.Utils
{
    public static class SampleHomeInfo
    {
        public static readonly string[] ImageUrls = new[]
{
            "https://img-v2.gtsstatic.net/reno/imagereader.aspx?imageurl=https%3A%2F%2Fm.sothebysrealty.com%2F1008i215%2F5w4wbqpc0v37m26e3ahhjcrsf4i215&option=N&h=472&permitphotoenlargement=false",
            "https://img-v2.gtsstatic.net/reno/imagereader.aspx?imageurl=https%3A%2F%2Fm.sothebysrealty.com%2F1008i215%2Fgfrashgyn79cmj6ghd93kr2eh6i215&option=N&h=472&permitphotoenlargement=false",
            "https://img-v2.gtsstatic.net/reno/imagereader.aspx?imageurl=https%3A%2F%2Fm.sothebysrealty.com%2F1008i215%2Fckvfe1gzq8rf49pwf7wpannpz0i215&option=N&h=472&permitphotoenlargement=false",
            "https://img-v2.gtsstatic.net/reno/imagereader.aspx?imageurl=https%3A%2F%2Fm.sothebysrealty.com%2F1008i215%2Fkd9bpmkaht7tmdycsa77hfvyy5i215&option=N&h=472&permitphotoenlargement=false",
            "https://img-v2.gtsstatic.net/reno/imagereader.aspx?imageurl=https%3A%2F%2Fm.sothebysrealty.com%2F1008i215%2F9xtb8fj7t6th4sj8jczg3v97s4i215&option=N&h=472&permitphotoenlargement=false",
            "https://img-v2.gtsstatic.net/reno/imagereader.aspx?imageurl=https%3A%2F%2Fm.sothebysrealty.com%2F1008i215%2F9xtb8fj7t6th4sj8jczg3v97s4i215&option=N&h=472&permitphotoenlargement=false",
            "https://img-v2.gtsstatic.net/reno/imagereader.aspx?imageurl=https%3A%2F%2Fm.sothebysrealty.com%2F1008i215%2Ffnw7dxx883ramp2rybkb9pxrq0i215&option=N&h=472&permitphotoenlargement=false",
            "https://img-v2.gtsstatic.net/reno/imagereader.aspx?imageurl=https%3A%2F%2Fm.sothebysrealty.com%2F1008i215%2F30e2s6ahjyep49tjxmmzvc5r17i215&option=N&h=472&permitphotoenlargement=false",
            "https://img-v2.gtsstatic.net/reno/imagereader.aspx?imageurl=https%3A%2F%2Fm.sothebysrealty.com%2F1008i215%2Ftqwn6zt0tnac40a8ekyn1q2dd4i215&option=N&h=472&permitphotoenlargement=false",
            "https://img-v2.gtsstatic.net/reno/imagereader.aspx?imageurl=https%3A%2F%2Fm.sothebysrealty.com%2F1008i215%2F5528f1nfn72vmepdyvqrs949j4i215&option=N&h=472&permitphotoenlargement=false",
            "https://img-v2.gtsstatic.net/reno/imagereader.aspx?imageurl=https%3A%2F%2Fm.sothebysrealty.com%2F1008i215%2Fxvyt24566y9b4zayhzarq8ssn2i215&option=N&h=472&permitphotoenlargement=false",
            "https://img-v2.gtsstatic.net/reno/imagereader.aspx?imageurl=https%3A%2F%2Fm.sothebysrealty.com%2F1008i215%2Fbhsxr4n9hmc84etbg5dzjj35p3i215&option=N&h=472&permitphotoenlargement=false",
            "https://img-v2.gtsstatic.net/reno/imagereader.aspx?imageurl=https%3A%2F%2Fm.sothebysrealty.com%2F1008i215%2F2t8c0fm0twzpms2ksj83cmkrk1i215&option=N&h=472&permitphotoenlargement=false",
            "https://img-v2.gtsstatic.net/reno/imagereader.aspx?imageurl=https%3A%2F%2Fm.sothebysrealty.com%2F1008i215%2Fvabdnk4f7vwq4c6nanvbqr4fn6i215&option=N&h=472&permitphotoenlargement=false",
            "https://img-v2.gtsstatic.net/reno/imagereader.aspx?imageurl=https%3A%2F%2Fm.sothebysrealty.com%2F1008i215%2F00y7jsby1at14ttd5fgwkms5a0i215&option=N&h=472&permitphotoenlargement=false",
            "https://img-v2.gtsstatic.net/reno/imagereader.aspx?imageurl=https%3A%2F%2Fm.sothebysrealty.com%2F1008i215%2F0rfakayag4y2mw6c94qs9j3hw7i215&option=N&h=472&permitphotoenlargement=false",
            "https://img-v2.gtsstatic.net/reno/imagereader.aspx?imageurl=https%3A%2F%2Fm.sothebysrealty.com%2F1008i215%2Fd94xp0g594symre3zhjm3jhy95i215&option=N&h=472&permitphotoenlargement=false",
            "https://img-v2.gtsstatic.net/reno/imagereader.aspx?imageurl=https%3A%2F%2Fm.sothebysrealty.com%2F1008i215%2F1y9490z743gqmtaq0t8s9y1b90i215&option=N&h=472&permitphotoenlargement=false",
            "https://img-v2.gtsstatic.net/reno/imagereader.aspx?imageurl=https%3A%2F%2Fm.sothebysrealty.com%2F1008i215%2Fst5t4et5h6e04hjmg0vrv4fb45i215&option=N&h=472&permitphotoenlargement=false",
            "https://img-v2.gtsstatic.net/reno/imagereader.aspx?imageurl=https%3A%2F%2Fm.sothebysrealty.com%2F1008i215%2F8q42c18wp68n4fjnhe206djmt5i215&option=N&h=472&permitphotoenlargement=false",
            "https://img-v2.gtsstatic.net/reno/imagereader.aspx?imageurl=https%3A%2F%2Fm.sothebysrealty.com%2F1008i215%2F22jvkhzk6ygymzpyyh90qbbcf4i215&option=N&h=472&permitphotoenlargement=false",
            "https://img-v2.gtsstatic.net/reno/imagereader.aspx?imageurl=https%3A%2F%2Fm.sothebysrealty.com%2F1008i215%2F4cfc7zdgeqeemp6r0vhjbkgdn7i215&option=N&h=472&permitphotoenlargement=false",
            "https://img-v2.gtsstatic.net/reno/imagereader.aspx?imageurl=https%3A%2F%2Fm.sothebysrealty.com%2F1008i215%2Fadtay20rmc64m02kczac3zk4d5i215&option=N&h=472&permitphotoenlargement=false"
        };

        public static readonly string[] Addresses = new[] 
        {
            "1 Bloor Street West",
            "88 Cumberland Street",
            "155 Yorkville Avenue",
            "200 Russell Hill Road",
            "10 Bellair Street",
            "50 Scollard Street",
            "77 Charles Street West",
            "80 Yorkville Avenue",
            "181 Davenport Road",
            "36 Hazelton Avenue",
            "1 St. Thomas Street",
            "206 Bloor Street West",
            "133 Hazelton Avenue",
            "25 Scrivener Square",
            "211 St. George Street",
            "170 Avenue Road",
            "89 Avenue Road",
            "100 Yorkville Avenue",
            "118 Yorkville Avenue",
            "7 Dale Avenue",
            "21 Park Lane Circle",
            "45 The Bridle Path",
            "67 Dunvegan Road",
            "10 Old Forest Hill Road",
            "15 Forest Hill Road",
            "299 Russell Hill Road",
            "9 High Point Road",
            "22 Teddington Park Avenue",
            "12 Ardwold Gate",
            "55 Dunloe Road",
            "101 Old Colony Road",
            "34 Forest Hill Road",
            "8 Castle Frank Road",
            "96 Warren Road",
            "73 Teddington Park Avenue",
            "25 Lytton Boulevard",
            "40 Kilbarry Road",
            "111 Roxborough Drive",
            "19 Glen Edyth Place",
            "26 Chestnut Park Road",
            "79 Farnham Avenue",
            "120 Forest Hill Road",
            "33 Whitehall Road",
            "91 Heath Street West",
            "18 Castle Knock Road",
            "60 Montclair Avenue",
            "101 Poplar Plains Road",
            "85 Bedford Road",
            "245 St. George Street",
            "11 Tranby Avenue",
            "123 Cottingham Street",
            "148 Macpherson Avenue",
            "44 Walmer Road",
            "308 Spadina Road",
            "272 Lonsdale Road",
            "178 Douglas Drive",
            "9 Crescent Road",
            "42 Roxborough Street West",
            "234 Balmoral Avenue",
            "7 Warren Road",
            "134 Cluny Drive",
            "220 Heath Street East",
            "31 Clarendon Avenue",
            "52 Russell Hill Road",
            "6 Ava Crescent",
            "88 Forest Hill Road",
            "17 Ardwold Gate",
            "45 South Drive",
            "222 Wychwood Park",
            "31 Hawthorn Avenue",
            "19 Highland Avenue",
            "24 Chestnut Park Road",
            "67 Douglas Drive",
            "80 South Drive",
            "100 Glen Road",
            "74 Edmund Avenue",
            "112 Park Road",
            "54 Castle Frank Road",
            "92 South Drive",
            "58 Roxborough Drive",
            "150 Tranby Avenue",
            "83 Bedford Road",
            "118 Hazelton Avenue",
            "48 Roxborough Street East",
            "90 Summerhill Avenue",
            "144 Macpherson Avenue",
            "60 Walker Avenue",
            "239 Glen Road",
            "77 Chestnut Park Road",
            "201 St. George Street",
            "12 Crescent Road",
            "36 South Drive",
            "108 Douglas Drive",
            "55 Roxborough Drive",
            "11 Glen Edyth Drive",
            "38 Whitehall Road",
            "81 Balmoral Avenue",
            "128 Tranby Avenue",
            "200 Forest Hill Road",
            "157 Roxborough Drive",
            "18 Ardwold Gate",
            "66 Cluny Drive",
            "29 South Hill Street"
        };

        public static readonly string[] Titles = new[]
        {
            "Skyline Penthouse Retreat",
            "The Yorkville Grand",
            "Hazelton Heights Haven",
            "Palace on the Park",
            "Modern Manor in the City",
            "Chateau Charles",
            "Rosedale Regal Residence",
            "The Avenue Crown",
            "Forest Hill Elite Estate",
            "Bridle Path Brilliance",
            "Cluny Castle",
            "The Hazelton Jewel",
            "Park Lane Prestige",
            "Summerhill Serenity",
            "Urban Oasis Penthouse",
            "Roxborough Elegance",
            "Luxury on Lonsdale",
            "Teddington Park Treasure",
            "Glen Edyth Grandeur",
            "The South Drive Stunner",
            "Midtown Masterpiece",
            "Davenport Deluxe",
            "Bloor Street Bliss",
            "Wychwood Wonder",
            "Castle Frank Classic",
            "The Belmont Estate",
            "Hilltop Horizon Home",
            "Vistas of Yorkville",
            "The Old Colony Classic",
            "Clarendon Crown Jewel",
            "Scollard Supreme",
            "The Urban Château",
            "The Macpherson Mansion",
            "Rosedale Retreat",
            "The Ardwold Enclave",
            "Skyview Sanctuary",
            "Russell Hill Royal",
            "The Bridle Gem",
            "Roxborough Heights",
            "Hazelton Heritage Home",
            "Modern Luxury Manor",
            "Penthouse on the Park",
            "The Castle Hill Classic",
            "Dale Estate of Elegance",
            "Lytton Living",
            "The Teddington Elite",
            "Glen Road Grandeur",
            "Yorkville Sky Villa",
            "The Avenue Residence",
            "Balmoral Brilliance",
            "Heath Street Hideaway",
            "The Summerhill Sanctuary",
            "Park Road Perfection",
            "Prestige on Poplar",
            "The Tranby Treasure",
            "The Glen Crescent Estate",
            "Luxury on Walker",
            "The Russell Hill Residence",
            "Bloor Skyline Estate",
            "The Bedford Legacy",
            "Castle Heights Haven",
            "The Lonsdale Luxe",
            "Hazelton Skyview",
            "Urban Luxury Retreat",
            "The Cottingham Classic",
            "Warren Road Wonder",
            "The Chestnut Park Charm",
            "High Point Haven",
            "Elite on Edmund",
            "The Avenue Skyview",
            "The Highland Home",
            "Dunvegan Dream",
            "The Douglas Delight",
            "Walmer Road Wonder",
            "The Bellair Estate",
            "South Drive Sophistication",
            "The Balmoral Belle",
            "Roxborough Splendor",
            "The St. George Signature",
            "The Clarendon Crown",
            "Park Lane Palace",
            "Bridle Path Panorama",
            "The Ardwold Retreat",
            "Hazelton Luxe Loft",
            "The Summerhill Splendor",
            "Elite Avenue Estate",
            "Davenport Park Place",
            "The Glencairn Gem",
            "Urban Pearl in Yorkville",
            "The Old Forest Hill Manor",
            "The Tranby Terraces",
            "Sky Manor on Spadina",
            "The Kilbarry Jewel",
            "Wychwood Prestige",
            "Poplar Plains Panorama",
            "The Russell Hill Elegance",
            "The Glen Edyth Grace",
            "Bloor West Penthouse",
            "The Yorkville Estate",
            "Hilltop Luxe Living",
            "Balmoral Bliss",
            "The Parkside Paradise"
        };
    }

}



